openapi: 3.0.0
servers:
  - url: https://api.mercadopago.com
info:
  title: Mercado Pago API Reference
  version: '1.0'
paths:
  /test_users:
    post:
      tags:
        - $ref: '#/tags/checkout-api'
        - $ref: '#/tags/checkout-pro'
      summary: Create Test User
      description: This endpoint handles http requests to create test_users
      parameters:
        - name: access_token
          in: query
          description: Access Token to Authenticate the request
          required: true
          schema:
            type: string
            example: "12123adfasdf123u4u"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                site_id:
                  type: string
                  description: site ID
                  required: true
                  example: "MLA"
                  enum:
                    - MPE --
                    - MSV --
                    - MPA --
                    - MRD --
                    - MLU --
                    - MLA --
                    - MLC --
                    - MCR --
                    - MPY --
                    - MBO --
                    - MNI --
                    - MHN --
                    - MCO --
                    - MEC --
                    - MLB --
                    - MGT --
                    - MLV --
                    - MLM --
                    - MCU -- 
      responses:
        '200':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 123
                  nickname:
                    type: string
                    example: "TEST45I5GYIH"
                  password:
                    type: string
                    example: "qatest6730"
                  site_status:
                    type: string
                    example: "active"
                  site_id:
                    type: string
                    example: "MLA"
                  email:
                    type: string
                    example: "test_user_123@testuser.com"
                  date_created:
                    type: string
                    example: "2021-11-04T12:02:35Z"
                  date_last_updated:
                    type: string
                    example: "2021-11-04T12:02:35Z"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorKey:
                    type: string
                    enum:
                      - 400--Bad-Request--invalid-site_id
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorKey:
                    type: string
                    enum:
                      - 403--Forbidden--authorization-the-caller-id-must-be-a-productive-user
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorKey:
                    type: string
                    enum:
                      - 500--Internal-Server-Error